version: '3.9'

services:

  samba:
    profiles:
      - nas
    image: dperson/samba:latest
    container_name: samba
    command: '-u "user;user" -s "share;/share;yes;no;no"'
    environment:
      - TZ=${tz}
    ports:
      - 139:139/tcp
      - 445:445/tcp
    volumes:
      - ${share}:/share
    restart: unless-stopped
    
  mosquitto:
    profiles:
      - mqtt
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${volume}/mosquitto/config:/mosquitto/config:rw
    restart: always
    
  deepstack:
    profiles:
      - deepstack      
    container_name: deepstack
    image: deepquestai/deepstack
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      VISION-FACE: 'True'
      MODE: High
    volumes:
      - ${volume}/deepstack:/datastore
      
  compreface-postgres-db:
    profiles:
      - compreface    
    image: postgres:11.5
    container_name: "compreface-postgres-db"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=frs
    volumes:
      - ${volume}/compreface:/var/lib/postgresql/data

  compreface-admin:   
    profiles:
      - compreface      
    image: exadel/compreface-admin:0.6.0
    container_name: "compreface-admin"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=jdbc:postgresql://compreface-postgres-db:5432/frs
      - SPRING_PROFILES_ACTIVE=dev
      - ENABLE_EMAIL_SERVER=false
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_USERNAME=
      - EMAIL_FROM=
      - EMAIL_PASSWORD=
      - ADMIN_JAVA_OPTS=-Xmx8g
    depends_on:
      - compreface-postgres-db
      - compreface-api

  compreface-api:  
    profiles:
      - compreface      
    image: exadel/compreface-api:0.6.0
    container_name: "compreface-api"
    restart: unless-stopped
    depends_on:
      - compreface-postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=jdbc:postgresql://compreface-postgres-db:5432/frs
      - SPRING_PROFILES_ACTIVE=dev
      - API_JAVA_OPTS=-Xmx8g
      - SAVE_IMAGES_TO_DB=true

  compreface-fe:   
    profiles:
      - compreface    
    image: exadel/compreface-fe:0.6.0
    container_name: "compreface-ui"
    restart: unless-stopped
    ports:
      - "7000:80"
    depends_on:
      - compreface-api
      - compreface-admin

  compreface-core:  
    profiles:
      - compreface      
    image: exadel/compreface-core:0.6.0
    container_name: "compreface-core"
    restart: unless-stopped
    environment:
      - ML_PORT=3000
      
  doubletake:
    profiles:
      - nvr
    container_name: doubletake
    image: jakowenko/double-take
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro    
      - ${volume}/doubletake:/.storage
    ports:
      - 3000:3000      
      
  frigate:
    profiles:
      - nvr  
    container_name: frigate
    privileged: true
    image: blakeblackshear/frigate:stable-amd64
    shm_size: "64mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${volume}/frigate/config.yaml:/config/config.yml:ro
      - ${share}/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000      
    ports:
      - 5000:5000
      - 1935:1935
    environment:
      FRIGATE_RTSP_PASSWORD: frigate
    restart: always
    
  baikal:
    profiles:
      - calendar
    image: eyalcohen/baikal:0.9.2
    container_name: baikal
    ports:
      - 3000:80
    volumes:
      - /etc/localtime:/etc/localtime:ro    
      - ${volume}/baikal/config:/var/www/baikal/config
      - ${volume}/baikal/data:/var/www/baikal/Specific
    restart: always

  agendav:
    profiles:
      - calendar  
    image: eyalcohen/agendav
    container_name: agendav
    volumes:
      - /etc/localtime:/etc/localtime:ro    
    environment:
      - AGENDAV_SERVER_NAME=127.0.0.1
      - AGENDAV_TITLE=Welcome to HomeAssistant Agendav Server
      - AGENDAV_FOOTER=Hosted by HomeAssistant
      - AGENDAV_ENC_KEY=my_encrypt10n_k3y
      - AGENDAV_CALDAV_SERVER=http://baikal.home:3000/cal.php
      - AGENDAV_TIMEZONE=${tz}
      - AGENDAV_LANG=en
      - AGENDAV_LOG_DIR=/tmp/
    depends_on:
      - baikal      
    ports:
      - 80:80
    restart: always    
