version: '3.9'

volumes:
  deepstack:
  compreface:

services:

  deepstack:
    profiles:
      - deepstack      
    container_name: deepstack
    image: deepquestai/deepstack
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      VISION-FACE: 'True'
      MODE: High
    volumes:
      - deepstack:/datastore

  compreface-postgres-db:
    profiles:
      - compreface    
    image: postgres:11.5
    container_name: "compreface-postgres-db"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=frs
    volumes:
      - compreface:/var/lib/postgresql/data

  compreface-admin:   
    profiles:
      - compreface      
    image: exadel/compreface-admin:0.6.0
    container_name: "compreface-admin"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=jdbc:postgresql://compreface-postgres-db:5432/frs
      - SPRING_PROFILES_ACTIVE=dev
      - ENABLE_EMAIL_SERVER=false
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_USERNAME=
      - EMAIL_FROM=
      - EMAIL_PASSWORD=
      - ADMIN_JAVA_OPTS=-Xmx8g
    depends_on:
      - compreface-postgres-db
      - compreface-api

  compreface-api:  
    profiles:
      - compreface      
    image: exadel/compreface-api:0.6.0
    container_name: "compreface-api"
    restart: unless-stopped
    depends_on:
      - compreface-postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=jdbc:postgresql://compreface-postgres-db:5432/frs
      - SPRING_PROFILES_ACTIVE=dev
      - API_JAVA_OPTS=-Xmx8g
      - SAVE_IMAGES_TO_DB=true

  compreface-fe:   
    profiles:
      - compreface    
    image: exadel/compreface-fe:0.6.0
    container_name: "compreface-ui"
    restart: unless-stopped
    ports:
      - "7000:80"
    depends_on:
      - compreface-api
      - compreface-admin

  compreface-core:  
    profiles:
      - compreface      
    image: exadel/compreface-core:0.6.0
    container_name: "compreface-core"
    restart: unless-stopped
    environment:
      - ML_PORT=3000
      
  doubletake:
    profile:
      - nvr
    container_name: doubletake
    image: jakowenko/double-take
    restart: unless-stopped
    volumes:
      - /double-take/.storage:/.storage
    ports:
      - 3000:3000      
