version: '3.9'

volumes:
  doubletake:
  deepstack:
  compreface:

services:

  deepstack:
    profiles:
      - deepstack      
    container_name: deepstack
    image: deepquestai/deepstack
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      VISION-FACE: 'True'
      MODE: High
    volumes:
      - deepstack:/datastore
      
  compreface-postgres-db:
    profiles:
      - compreface    
    image: postgres:11.5
    container_name: "compreface-postgres-db"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=frs
    volumes:
      - compreface:/var/lib/postgresql/data

  compreface-admin:   
    profiles:
      - compreface      
    image: exadel/compreface-admin:0.6.0
    container_name: "compreface-admin"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=jdbc:postgresql://compreface-postgres-db:5432/frs
      - SPRING_PROFILES_ACTIVE=dev
      - ENABLE_EMAIL_SERVER=false
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_USERNAME=
      - EMAIL_FROM=
      - EMAIL_PASSWORD=
      - ADMIN_JAVA_OPTS=-Xmx8g
    depends_on:
      - compreface-postgres-db
      - compreface-api

  compreface-api:  
    profiles:
      - compreface      
    image: exadel/compreface-api:0.6.0
    container_name: "compreface-api"
    restart: unless-stopped
    depends_on:
      - compreface-postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=jdbc:postgresql://compreface-postgres-db:5432/frs
      - SPRING_PROFILES_ACTIVE=dev
      - API_JAVA_OPTS=-Xmx8g
      - SAVE_IMAGES_TO_DB=true

  compreface-fe:   
    profiles:
      - compreface    
    image: exadel/compreface-fe:0.6.0
    container_name: "compreface-ui"
    restart: unless-stopped
    ports:
      - "7000:80"
    depends_on:
      - compreface-api
      - compreface-admin

  compreface-core:  
    profiles:
      - compreface      
    image: exadel/compreface-core:0.6.0
    container_name: "compreface-core"
    restart: unless-stopped
    environment:
      - ML_PORT=3000
      
  doubletake:
    profiles:
      - nvr
    container_name: doubletake
    image: jakowenko/double-take
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro    
      - doubletake:/.storage
    ports:
      - 3000:3000      
      
  frigate:
    profiles:
      - nvr  
    container_name: frigate
    privileged: true
    image: blakeblackshear/frigate:stable-amd64
    shm_size: "64mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${share}/frigate/config.yml:/config/config.yml:ro
      - ${share}/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000      
    ports:
      - 5000:5000
      - 1935:1935
    environment:
      FRIGATE_RTSP_PASSWORD: frigate
    restart: always 
