version: '3.9'

volumes:
  deepstack:

services:

  deepstack:
    profiles:
      - deepstack      
    container_name: deepstack
    image: deepquestai/deepstack
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      VISION-FACE: 'True'
      MODE: High
    volumes:
      - deepstack:/datastore
